#' Check model
#'
#' This function checks performance of targets with regards to prediction errors
#'
#' @param .data A tidy-timeseries data generated from \code{data_join}
#' @param plans A plan that generated by \code{planner}
#' @param targets A prior
#' @param model_size
check_model <- function(.data, plans, targets, model_size = 3) {
  .measure_prederrs <- function(checked_data,
                                incprobs = NULL,
                                coefs = NULL) {
    test_period <- checked_data$mea.idxs[1]:checked_data$mea.idxs[2]

    res <- ZDBayes::ZDSAD(checked_data$target.data,
                          checked_data$ref.idxs,
                          checked_data$mea.idxs,
                          prior.incprobs = checked_data$incprobs,
                          coef.est = checked_data$coefs)

    response <- res$series$response[test_period] %>% na.omit %>% abs
    point.pred <- res$series$point.pred[test_period] %>% na.omit %>% abs
    pred.errors <- abs(response - point.pred) / abs(response)
    model.coef <- colMeans(res$model$ZDBayes.model$coefficients)
    model.coef <- model.coef[2:length(model.coef)]

    return(list(pred_errs = pred.errors %>% as.vector,
                model_coef = model.coef))
  }

  # TODO: Use a better way of storing data in two array. I think there is, so
  # ask this in Stack Overflow.
  set_of_pred_errors <- double()
  set_of_incprobs <- double()
  names.of.exp <- c()

  for (i in 1:nrow(plans)) {
    cat(i, "/", nrow(plans), "...\n")

    plan <- plans[i, ]

    name.of.exp <- paste0(plan[["training_period"]], "|",
                          plan[["testing_period"]])
    checked_data <- transform_data(.data, targets, plan) %>%
                    validate_data(plan)
    checked_data$incprobs <- get_prior_incprobs(checked_data, targets, target_name)
    checked_data$coefs <- get_prior_coefs(checked_data, targets, target_name)

    if (checked_data$valid == T) {
      res <- checked_data %>% .measure_prederrs
      pred.errs <- res[["pred_errs"]] %>% as.vector
      model.coef <- res[["model_coef"]]

      set_of_pred_errors <- rbind(set_of_pred_errors, summary(pred.errs))
      set_of_incprobs <- rbind(set_of_incprobs, model.coef)

      names.of.exp <- c(names.of.exp, name.of.exp)
    }
  }

  set_of_pred_errors <- as.data.frame(set_of_pred_errors)
  set_of_incprobs <- as.data.frame(set_of_incprobs)

  row.names(set_of_pred_errors) <- names.of.exp
  row.names(set_of_incprobs) <- names.of.exp

  return(list(pred_errors = set_of_pred_errors,
              model_coefs = set_of_incprobs))
}
